global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'easywin-monitor'

scrape_configs:
  - job_name: 'bet_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['bet-service:8080']
        labels:
          application: 'Bet Service'
  - job_name: 'chat_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['chat-service:8080']
        labels:
          application: 'Chat Service'
  - job_name: 'notification_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8080']
        labels:
          application: 'Notification Service'
  - job_name: 'ticket_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ticket-service:8080']
        labels:
          application: 'Ticket Service'
  - job_name: 'wallet_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['wallet-service:8080']
        labels:
          application: 'Wallet Service'