---
version: '3.7'
services:
  mysql-ticket:
    image: "mysql:8.0.31"
    container_name: mysql-ticket
    environment:
      MYSQL_DB: ticket-service
      MYSQL_USER: patryk
      MYSQL_PASSWORD: Mysql304575!
      MYSQL_ROOT_PASSWORD: Mysql304575!
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3308:3308"
    restart: unless-stopped

  mysql-wallet:
    image: "mysql:8.0.31"
    container_name: mysql-wallet
    environment:
      MYSQL_DB: wallet-service
      MYSQL_USER: patryk
      MYSQL_PASSWORD: Mysql304575!
      MYSQL_ROOT_PASSWORD: Mysql304575!
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3307:3307"
    restart: unless-stopped

  mongodb-bet:
    image: "mongo:4.4.3"
    container_name: mongodb-bet
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./mongodb-bet:/data/db
    restart: always

  keycloak-mysql:
    image: mysql:8.0.31
    container_name: keycloak-mysql
    volumes:
      - ./mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: patryk
      MYSQL_PASSWORD: Mysql304575!
      MYSQL_ROOT_PASSWORD: Mysql304575!

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  discovery-server:
    image: dr34mer99/discovery-server:latest
    container_name: discovery-server
    pull_policy: always
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin

  api-gateway:
    image: dr34mer99/api-gateway:latest
    container_name: api-gateway
    pull_policy: always
    ports:
      - "8181:8080"
    expose:
      - "8181"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
    depends_on:
      - zipkin
      - discovery-server
      - keycloak


  bet-service:
    image: dr34mer99/bet-service:latest
    container_name: bet-service
    pull_policy: always
    links:
      - mongodb-bet:bet_db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb-bet
      - api-gateway
      - discovery-server

  chat-service:
    image: dr34mer99/chat-service:latest
    container_name: chat-service
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - zipkin
      - api-gateway
      - discovery-server

  notification-service:
    image: dr34mer99/notification-service:latest
    container_name: notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - broker
      - discovery-server
      - api-gateway

  wallet-service:
    image: dr34mer99/wallet-service:latest
    container_name: wallet-service
    links:
      - mysql-wallet:wallet_db
    environment:
      - SPRING_ACTIVE_PROFILES=docker
    depends_on:
      - zipkin
      - discovery-server
      - api-gateway
      - mysql-wallet

  ticket-service:
    image: dr34mer99/ticket-service:latest
    container_name: ticket-service
    links:
      - mysql-ticket:ticket_db
    environment:
      - SPRING_ACTIVE_PROFILES=docker
    depends_on:
      - api-gateway
      - zipkin
      - mysql-ticket
      - bet-service
      - discovery-server
      - broker
