CREATE DATABASE IF NOT EXISTS ticket_service;

-- CREATE USER 'root'@'172.19.0.3' IDENTIFIED BY 'password';
--
-- GRANT ALL PRIVILEGES ON *.* TO 'root'@'172.19.0.3' WITH GRANT OPTION;
--
-- FLUSH PRIVILEGES;